import javax.swing.*;
import java.awt.*;
import java.io.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

/**
 * @Description
 * @Author 王传鑫
 * @Date 2019/1/14
 */
public class MainUI extends JFrame{

    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initData();
        initComponents();
    }

    private static List<String> names=new ArrayList<>();
    private static List<String> runnableNames=new ArrayList<>();
    private static List<String> selectedNames=new ArrayList<>();
    private static Integer createNum=0;
    private static boolean isstart=false;

    class ImagePanel extends JPanel {
        Dimension d;
        Image image;

        public ImagePanel(Dimension d, Image image) {
            super();
            this.d = d;
            this.image = image;
        }

        @Override
        public void paintComponent(Graphics g) {
            super.paintComponent(g);
            g.drawImage(image, 0, 0, d.width, d.height, this);
            MainUI.this.repaint();
        }
    }
    private void initData(){
        Toolkit kit = Toolkit.getDefaultToolkit(); // 定义工具包
        Dimension screenSize = kit.getScreenSize(); // 获取屏幕的尺寸
        int screenWidth = screenSize.width/2; // 获取屏幕的宽
        int screenHeight = screenSize.height/2; // 获取屏幕的高
        int height = this.getHeight();
        int width = this.getWidth();
        setLocation((screenWidth-width)/2, (screenHeight-height)/2);
        names.clear();
        selectedNames.clear();
        try {

            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) { e.printStackTrace();

        }
        ImageIcon imageIcon=new ImageIcon(this.getClass().getResource("/bg.jpg"));
        JLabel lbBg = new JLabel(imageIcon);
        lbBg.setBounds(0, 0, this.getWidth(), this.getHeight());
        getContentPane().add(lbBg);
        Image img = Toolkit.getDefaultToolkit ().getImage (this.getClass().getResource("/logo.png"));

        ImagePanel imagePanel = new ImagePanel(screenSize, imageIcon.getImage());
        setContentPane(imagePanel);
        setIconImage(img);
//        selectedRunnable.setDaemon(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        startBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        totleText = new javax.swing.JTextField();
        selectedNum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        importMenu = new javax.swing.JMenuItem();
        exportMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        startBtn.setIcon(new javax.swing.ImageIcon("E:\\netbeanws\\ContactEditor\\resource\\开始_1.png")); // NOI18N
        startBtn.setText("一键生成");
        startBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("总人数");

        totleText.setEditable(false);
        totleText.setText("0");

        selectedNum.setText("0");

        jLabel2.setText("生成人数");

        jMenu1.setText("File");

        importMenu.setText("导入数据");
        importMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importMenuActionPerformed(evt);
            }
        });
        jMenu1.add(importMenu);

        exportMenu.setText("导出数据");
        exportMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportMenuActionPerformed(evt);
            }
        });
        jMenu1.add(exportMenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(totleText, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(selectedNum, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(104, 104, 104)
                                .addComponent(startBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(selectedNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(startBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(totleText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>





    private void startBtnActionPerformed(java.awt.event.ActionEvent evt) {
        String numStr= selectedNum.getText();
        if(numStr.matches("\\d+")){

            Integer num=Integer.parseInt(numStr);
            if(num==0){
                JOptionPane.showMessageDialog(null, " 请输入大于0数字", " 提示", JOptionPane.PLAIN_MESSAGE);
                return;
            }
            if (num>names.size()){
                JOptionPane.showMessageDialog(null, " 输入数字大于总人数", " 提示", JOptionPane.PLAIN_MESSAGE);

                return;
            }
            createNum= num;
            runnableNames.clear();
            for (String s:names) {
                runnableNames.add(s);
            }
                Random random=new Random(71);
            selectedNames.clear();

            for (int i = 0; i < createNum; i++) {
                    int idx= random.nextInt(runnableNames.size());
                    String name =runnableNames.get(idx);
                    selectedNames.add(name);
                    runnableNames.remove(name);
            }
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            JOptionPane.showMessageDialog(null, " 生成完成", " 提示", JOptionPane.PLAIN_MESSAGE);

        }else{
            JOptionPane.showMessageDialog(null, " 请输入数字", " 提示", JOptionPane.PLAIN_MESSAGE);
        }
    }


    private void importMenuActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        JFileChooser fileChooser=new JFileChooser();
        fileChooser.setFileSelectionMode(0);

        fileChooser.showDialog(null,"请选择文件");
        File file=fileChooser.getSelectedFile();
        if(file==null){
            return;
        }
        BufferedReader reader=null;
        try {
             reader=new BufferedReader(new InputStreamReader(new FileInputStream(file),"GBK"));
            String text=null;
            while (null!=(text=reader.readLine())){
                names.add(text.trim().replaceAll("\n",""));
            }
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }catch (IOException e) {
            e.printStackTrace();
        }finally {
            if(reader!=null){
                try {
                    reader.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
            totleText.setText(names.size()+"");
            startBtn.setEnabled(true);
            JOptionPane.showMessageDialog(null, " 导入成功", " 导入名单", JOptionPane.PLAIN_MESSAGE);
        }
    }

    private void exportMenuActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        JFileChooser fileChooser=new JFileChooser();
        fileChooser.setFileSelectionMode(1);

        fileChooser.showDialog(null,"请选择文件");
        File file=fileChooser.getSelectedFile();
        if(file==null){
            return;
        }
        if(selectedNames.size()!=0){

            BufferedWriter writer=null;
            LocalDateTime dateTime=LocalDateTime.now();
            DateTimeFormatter format = DateTimeFormatter.ofPattern("yyyyMMddHHmmss");
            String suffer=dateTime.format(format);
            File exportData= new File(file.getPath()+String.format("\\获奖名单%s.txt",suffer));
            if(exportData.exists()){
                exportData.deleteOnExit();
            }
            try {
                writer=new BufferedWriter(new OutputStreamWriter(new FileOutputStream(exportData),"GBK"));
               for(String name:selectedNames){
                   writer.write(name);
                   writer.newLine();
               }
            } catch (UnsupportedEncodingException e) {
                e.printStackTrace();
            } catch (FileNotFoundException e) {
                e.printStackTrace();
            }catch (IOException e) {
                e.printStackTrace();
            }finally {
                if(writer!=null){
                    try {
                        writer.close();
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                }
                JOptionPane.showMessageDialog(null, " 导出完成", " 提示", JOptionPane.PLAIN_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, " 还没有中奖名单", " 提示", JOptionPane.PLAIN_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify
    // Variables declaration - do not modify
    private javax.swing.JMenuItem exportMenu;
    private javax.swing.JMenuItem importMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField selectedNum;
    private javax.swing.JButton startBtn;
    private javax.swing.JTextField totleText;

    // End of variables declaration
}
